apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bosgenesis-k8s-data-ingestion-agent
  namespace: bosgenesis
  labels:
    app.kubernetes.io/name: bosgenesis-k8s-data-ingestion-agent
    app.kubernetes.io/part-of: bosgenesis
spec:
  ingressClassName: nginx
  rules:
    - host: data-ingestion-agent.bosgenesis.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bosgenesis-k8s-data-ingestion-agent
                port:
                  name: http

