apiVersion: v1
kind: Service
metadata:
  name: bosgenesis-k8s-data-ingestion-agent
  namespace: bosgenesis
  labels:
    app.kubernetes.io/name: bosgenesis-k8s-data-ingestion-agent
    app.kubernetes.io/part-of: bosgenesis
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: bosgenesis-k8s-data-ingestion-agent
  ports:
    - name: http
      port: 8080
      targetPort: http

