apiVersion: v1
kind: ServiceAccount
metadata:
  name: bosgenesis-k8s-data-ingestion-agent
  namespace: bosgenesis
  labels:
    app.kubernetes.io/name: bosgenesis-k8s-data-ingestion-agent
    app.kubernetes.io/part-of: bosgenesis

