apiVersion: v1
kind: Service
metadata:
  name: {{ include "data-ingestion-agent.name" . }}
  namespace: {{ include "data-ingestion-agent.namespace" . }}
  labels:
    {{- include "data-ingestion-agent.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "data-ingestion-agent.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http

